FROM node:14-alpine
WORKDIR /usr/src/client
COPY package*.json \
  vue.config.js \
  babel.config.js \
  Makefile /usr/src/client/
COPY . /usr/src/client
RUN apk add make \
  && make build
EXPOSE 8080
CMD npm run serve